jobs:
  include:
    - stage: build application
      script:
        - mvn compile
    - stage: deploy to staging
      script: skip
      deploy:
        provider: heroku
        api_key: $HerokuKey
        app: mega-pokedex
