language: java
jdk: oraclejdk8

jobs:
  include:
    - stage: build application
      script:
        - mvn compile
    - stage: static code analysis
      addons:
        sonarcloud:
          organization: "mega-pokedex"
          token: $SonarToken
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    - stage: deploy to staging
      script: skip
      deploy:
        provider: heroku
        api_key: $HerokuKey
        app: mega-pokedex-staging
#
# insert shit
#
    - stage: deploy to production
      script: skip
      deploy:
        provider: heroku
        api_key: $HerokuKey
        app: mega-pokedex
