jobs:
  include:
    - stage: build application
      script:
        - mvn compile
    - stage: static code analysis
      addons:
        sonarcloud:
          organization: "mega-pokedex"
          token: $SonarToken
      script:
        - mvn clean install sonar:sonar -Dsonar.host.url=https:/sonarqube.com -Dsonar.login=${SONARQUBE_TOKEN}
    - stage: deploy to staging
      script: skip
      deploy:
        provider: heroku
        api_key: $HerokuKey
        app: mega-pokedex-staging
    - stage: deploy to production
      script: skip
      deploy:
        provider: heroku
        api_key: $HerokuKey
        app: mega-pokedex
    - stage: build documantation
      script:
        - mvn javadoc:javadoc
        - cd ..
        - git clone https://github.com/mega-pokedex/doc.git
        - rm -rf docs/generated
        - cp -r application/target/site/apidocs docs/generated/
        - cd docs
        - git add .
        - git commit -m "update documentation"
        - git push "https://${TRAVIS_GITHUB_TOKEN}@github.com/mega-pokedex/doc.git" master
