conf = YAML.load_file("env.yml")

jobs:
  include:
    - stage: build application
      script:
        - mvn compile
    - stage: deploy to staging
      script: skip
      deploy:
        provider: heroku
        api_key: conf.fetch('key')['keyTravis']
        app: pokedexBackend
